#cloud-config

coreos:
  update:
    reboot-strategy: off

  units:
    - name: pypy.service
      command: start

write-files:
  - path: /etc/systemd/system/pypy.service
    permisions: '0644'
    content: |
      [Unit]
      Description=Install pypy
      Requires=network-online.target
      After=network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/opt/bin/install-pypy


  - path: /opt/bin/install-pypy
    permissions: '0755'
    content: |
      #!/bin/bash

      set -e
      HOME=/home/core
      cd

      if [[ -e $HOME/.bootstrapped ]]; then
          exit 0
      fi

      PYPY_VERSION=2.4.0

      wget -O - https://bitbucket.org/pypy/pypy/downloads/pypy-$PYPY_VERSION-linux64.tar.bz2 |tar -xjf -
      mv -n pypy-$PYPY_VERSION-linux64 pypy

      ## library fixup
      mkdir -p pypy/lib
      ln -snf /lib64/libncurses.so.5.9 $HOME/pypy/lib/libtinfo.so.5

      mkdir -p $HOME/bin

      cat > $HOME/bin/python <<EOF
      #!/bin/bash
      LD_LIBRARY_PATH=$HOME/pypy/lib:$LD_LIBRARY_PATH exec $HOME/pypy/bin/pypy "\$@"
      EOF

      chmod +x $HOME/bin/python
      $HOME/bin/python --version

      touch $HOME/.bootstrapped
